//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int Id { get; set; }
        public int Nota { get; set; }
        public string Comentario { get; set; }
        public int JugadorCalificadorId { get; set; }
        public int JugadorCalificadoId { get; set; }
        public int PartidoId { get; set; }
    
        public virtual Jugador Calificador { get; set; }
        public virtual Jugador Calificado { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
