//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infraccion
    {
        public int Id { get; set; }
        public string Fecha { get; set; }
        public string Motivo { get; set; }
        public int JugadorId { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
