//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int Id { get; set; }
        public int PartidoId { get; set; }
        public int JugadorId { get; set; }
        public int TipoInscripcionId { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> EquipoId { get; set; }
    
        public virtual Partido Partido { get; set; }
        public virtual Jugador Jugador { get; set; }
        public virtual TipoInscripcion TipoInscripcion { get; set; }
        public virtual Equipo Equipo { get; set; }
    }
}
