//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public Jugador()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
            this.CalificacionesDadas = new HashSet<Calificacion>();
            this.CalificacionesRecibidas = new HashSet<Calificacion>();
            this.Infraccion = new HashSet<Infraccion>();
            this.Amigos = new HashSet<Amistad>();
            this.Amigos1 = new HashSet<Amistad>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apodo { get; set; }
        public System.DateTime Fecha_Nac { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Handicap { get; set; }
    
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        public virtual ICollection<Calificacion> CalificacionesDadas { get; set; }
        public virtual ICollection<Calificacion> CalificacionesRecibidas { get; set; }
        public virtual ICollection<Infraccion> Infraccion { get; set; }
        public virtual ICollection<Amistad> Amigos { get; set; }
        public virtual ICollection<Amistad> Amigos1 { get; set; }


        public string HandicapColor
        {
            get
            {
                if (this.Handicap != null && this.Handicap > 8)
                    return "blue";
                else return "black";
            }
        }

        public bool CumpleCon(FiltroJugador filtro)
        {
                return filtro.cumple(this);
        
        }
    }
}
