//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Jugador> JugadorSet { get; set; }
        public DbSet<Partido> PartidoSet { get; set; }
        public DbSet<Inscripcion> InscripcionSet { get; set; }
        public DbSet<Calificacion> CalificacionSet { get; set; }
        public DbSet<EstadoPartido> EstadoPartidoSet { get; set; }
        public DbSet<Infraccion> InfraccionSet { get; set; }
        public DbSet<Amistad> AmistadSet { get; set; }
        public DbSet<TipoInscripcion> TipoInscripcionSet { get; set; }
        public DbSet<Equipo> EquipoSet { get; set; }
    }
}
