//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        public Partido()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Calificaciones = new HashSet<Calificacion>();
            this.Equipo = new HashSet<Equipo>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Administrador { get; set; }
        public int EstadoPartidoId { get; set; }
    
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        public virtual ICollection<Calificacion> Calificaciones { get; set; }
        public virtual EstadoPartido EstadoPartido { get; set; }
        public virtual ICollection<Equipo> Equipo { get; set; }
    }
}
