//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Futbol5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoInscripcion
    {
        public TipoInscripcion()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
    }
}
